### ISSUE TITLE
Create a module for Header metadata retrieval

### ISSUE THREAD

**Issue by gpsyrou** [gpsyrou/tube-virality#3]
Purpose of this module will be to create the main functionality to retrieve the "header" level metadata for a YouTube video. Specifically, we want to build a module which, given a list of YouTube video ids, it will be able to retrieve a collection of information, such as:

0. Video_id
1. Video Title
2. Channel/Creator who uploaded the video (channel_id, channel_name)
3. Video Description
4. Date posted (upload date)
5. Genre/Video Category
6. Locations that it is available
7. Duration

**Comment by limiu82214** [comment]
did you mean migrate func main's code to dataretriver.go ?

**Comment by gpsyrou** [comment]
> did you mean migrate func main's code to dataretriver.go ?

The initial plan was to migrate some code that I already have in a private repository - but i think it's better to re-write the logic as I want to have the data retrieval module in Golang for learning + performance purposes.
