### ISSUE TITLE
Fix folder structure 

### ISSUE THREAD

**Issue by gpsyrou** [gpsyrou/tube-virality#5]

**Comment by limiu82214** [comment]
I try to use [project-layout](https://github.com/golang-standards/project-layout) to change folder structure, have a look!

**Comment by gpsyrou** [comment]
> I try to use [project-layout](https://github.com/golang-standards/project-layout) to change folder structure, have a look!

Thanks for sharing this - I am quite new to Go so I am learning it atm. This is very useful - I'll review the PR
